embryoscope_credentials:
  'Vila Mariana':    
    ip: '10.250.115.39'
    login: 'WEB'
    password: 'web'
    port: 4000
    enabled: true
  'Ibirapuera':      
    ip: '10.250.110.208'
    login: 'WEB'
    password: 'web'
    port: 4000
    enabled: true
  'Belo Horizonte':  
    ip: '192.168.215.43'
    login: 'WEB'
    password: 'web'
    port: 4000
    enabled: true
  'Brasilia':        
    ip: '192.168.1.20'
    login: 'WEB'
    password: 'web'
    port: 4000
    enabled: true
  'Salvador':        
    ip: '10.2.0.70'
    login: 'WEB'
    password: 'web'
    port: 4000
    enabled: false  # Not working yet

database:
  path: '../database/embryoscope_incremental.duckdb'
  schema: 'embryoscope'

extraction:
  rate_limit_delay: 0.1  # 10 requests per second (0.1s between requests)
  max_workers: 4  # One worker per clinic (4 enabled clinics)
  clinic_parallel_workers: 1  # Sequential requests within each clinic
  max_retries: 3
  timeout: 10
  batch_size: 1000
  parallel_processing: true
  token_refresh_patients: 2000  # refresh token every N patients (less aggressive)
  token_refresh_treatments: 5000  # refresh token every N treatments (less aggressive)
  log_level: INFO  # DEBUG, INFO, WARNING, ERROR
  log_empty_responses: false  # whether to log empty embryo data responses

logging_level: INFO  # DEBUG, INFO, WARNING, ERROR 
